"""
Saarthi's conversational layer.

If OPENAI_API_KEY is configured, replies are generated by OpenAI, grounded
in the customer's real profile/goals/risk/nudges via a system prompt. If no
key is configured -- e.g. running this prototype fully offline -- Saarthi
falls back to a deterministic, still personalized templated responder, so the
product demos end-to-end without requiring anyone to hold a paid API key.
"""
from app.config import settings

FALLBACK_INTENTS = [
    (("risk", "profile", "aggressive", "conservative", "moderate"), "risk"),
    (("goal", "retirement", "education", "home", "vacation"), "goal"),
    (("sip", "invest", "equity", "debt", "allocation", "portfolio"), "invest"),
    (("score", "health"), "score"),
    (("hi", "hello", "hey", "namaste"), "greeting"),
]


def _match_intent(message: str) -> str:
    msg = message.lower()
    for keywords, intent in FALLBACK_INTENTS:
        if any(k in msg for k in keywords):
            return intent
    return "generic"


def _fallback_reply(message: str, context: dict) -> str:
    intent = _match_intent(message)
    name = context.get("name", "there")
    risk_label = context.get("risk_label", "moderate")
    score = context.get("wealth_health_score")
    goals = context.get("goals", [])

    if intent == "greeting":
        return f"Hi {name}! I'm Saarthi, your wealth avatar. Ask me about your goals, risk profile, or portfolio."

    if intent == "risk":
        return (
            f"Based on your spending and investment behaviour, I've profiled you as '{risk_label}'. "
            f"That's inferred from your savings rate, SIP consistency and goal horizon — not a one-time form — "
            f"so it updates automatically as your habits change."
        )

    if intent == "goal":
        if not goals:
            return "You don't have any goals set up yet — want to create one, like retirement or a home down payment?"
        lines = [f"'{g['name']}' is {g['funded_pct']}% funded" + ("" if g["on_track"] else " and falling behind schedule") for g in goals]
        return "Here's where your goals stand: " + "; ".join(lines) + "."

    if intent == "invest":
        return (
            f"Given your '{risk_label}' profile, I'd suggest a glide-path allocation weighted toward equity "
            f"if your goals are long-horizon, tapering to debt as you get closer. Check the Recommendations "
            f"tab for the exact split and why."
        )

    if intent == "score" and score is not None:
        return f"Your Wealth Health Score is {score}/100, based on your savings rate, SIP discipline, diversification and credit health."

    return (
        "I can help with your goals, risk profile, recommended allocation, or nudges — "
        "what would you like to look at?"
    )


def _llm_reply(message: str, context: dict) -> str | None:
    if not settings.openai_api_key:
        return None
    try:
        import openai
    except ImportError:
        return None

    system_prompt = (
        "You are Saarthi, an AI wealth-advisory avatar embedded in IDBI Bank's mobile banking app. "
        "You give warm, concise (2-4 sentence), explainable wealth advice to a mass-retail customer. "
        "Always ground your answer in the customer context provided, never invent numbers, and where "
        "relevant mention *why* (explainability), since advice must be auditable for SEBI/RBI compliance. "
        f"Customer context: {context}"
    )
    try:
        client = openai.OpenAI(api_key=settings.openai_api_key)
        resp = client.chat.completions.create(
            model=settings.openai_model,
            max_tokens=300,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": message},
            ],
        )
        content = resp.choices[0].message.content
        if isinstance(content, list):
            return "".join(getattr(part, "text", "") for part in content)
        return content
    except Exception:
        return None  # any API/network error silently falls back


def get_avatar_reply(message: str, context: dict) -> dict:
    llm_text = _llm_reply(message, context)
    if llm_text:
        return {"reply": llm_text, "source": "llm"}
    return {"reply": _fallback_reply(message, context), "source": "fallback"}
